name       : kolourpaint
version    : 17.12.2
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kolourpaint-17.12.2.tar.xz : ecb0aa0794baddcf6626d50f2af9d8b112abd08e96b7d337ce3c3cb065caa249
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
optimize   : lto
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
