name       : kolourpaint
version    : 19.12.3
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kolourpaint-19.12.3.tar.xz : 7c134da2feb75a87bfda6b4265ef705868a9be03d70a828111a2869ca0b517b1
homepage   : https://kde.org/applications/graphics/org.kde.kolourpaint
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
