name       : kolourpaint
version    : 17.08.1
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kolourpaint-17.08.1.tar.xz : 75af69ce07e8ce2a8c0513b8e216a81b6b7047a9caff44826bfc19934d418ea1
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
