name       : kolourpaint
version    : 17.12.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/kolourpaint-17.12.0.tar.xz : b4fc71915638bf640999376cf29138c9c1c543fe33d4dd8e4ecb3a65556894dd
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
optimize   : lto
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
