name       : kolourpaint
version    : 21.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kolourpaint-21.04.1.tar.xz : aa212fc8af0c74110651579b5cad87046aadcdf99450adac596f1beb201ed074
homepage   : https://kde.org/applications/graphics/org.kde.kolourpaint
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - ktextwidgets-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
