name       : kolourpaint
version    : 18.12.3
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kolourpaint-18.12.3.tar.xz : 450b714f0d73b59d31c4ceda142a3496d14e51d84b8c8968548a15e05c138f98
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
