name       : kolourpaint
version    : 18.04.1
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/kolourpaint-18.04.1.tar.xz : fe73b63961b011552a8eb179afe907662c4c67e800ba4b0a914871b8d3acdbd1
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
optimize   : lto
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
