name       : kolourpaint
version    : 18.04.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kolourpaint-18.04.0.tar.xz : 7917e35daafa18288c04d1c810d70a996d5829748b15e93bf4f0dc45080f60a1
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
optimize   : lto
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
