name       : kolourpaint
version    : 20.08.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kolourpaint-20.08.3.tar.xz : 3047607a89e9f840e6013dae2c0f6a5d46d45781201c9499ee7994b2ac7dc434
homepage   : https://kde.org/applications/graphics/org.kde.kolourpaint
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
