name       : kolourpaint
version    : 23.04.3
release    : 72
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kolourpaint-23.04.3.tar.xz : 3b49af6894631ee87bca72236d3a44bec2af303a6542e8a4710585a5a7d969a9
homepage   : https://kde.org/applications/graphics/org.kde.kolourpaint
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - ktextwidgets-devel
    - libksane-devel
rundeps    :
    - breeze
    - breeze-icons
    - kimageformats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
