name       : kolourpaint
version    : 19.08.3
release    : 31
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kolourpaint-19.08.3.tar.xz : aac61cfc561b4d4759b086508c53c525db6899ae11a2400c4ca701fcb5649c8d
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
