name       : kolourpaint
version    : 18.08.1
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kolourpaint-18.08.1.tar.xz : 9596f6298ed6782b1fd76b0941d9977785ab576a49e738113600d01950fa3b80
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
