name       : kolourpaint
version    : 22.04.1
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kolourpaint-22.04.1.tar.xz : 4d5096c7e40a592583f597ff388b3bc7c64e5b75f1b12e73b18e4bd7b777afeb
homepage   : https://kde.org/applications/graphics/org.kde.kolourpaint
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(Qt5Widgets)
    - kdoctools-devel
    - kguiaddons-devel
    - kio-devel
    - ktextwidgets-devel
    - libksane-devel
rundeps    :
    - breeze
    - breeze-icons
    - kimageformats
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
