name       : kolourpaint
version    : 17.12.1
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kolourpaint-17.12.1.tar.xz : 59add70f59a9bfc7df469eb59d1016308a19acfe5d7f0a8e3fe5bc2a613bbfb1
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
optimize   : lto
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
