name       : kolourpaint
version    : 17.12.3
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kolourpaint-17.12.3.tar.xz : 1c0df432c88140c26d3e379a79b99d4c4c71dc75f492d9c6e36bba1ea71f6d97
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
optimize   : lto
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
