name       : kolourpaint
version    : 17.08.2
release    : 5
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kolourpaint-17.08.2.tar.xz : 96d44611e8afaa5f65f54ad9efb3c4e295857f5efc07e842a980c03600ff6e95
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - extra-cmake-modules
    - kdelibs4support-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
