name       : kolourpaint
version    : 16.12.0
release    : 1
source     :
    - http://download.kde.org/stable/applications/16.12.0/src/kolourpaint-16.12.0.tar.xz : 8e5644951d3327329b45cec28519796a8866e2276d046278a523ce00456f5775
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : multimedia.graphics
summary    : KolourPaint is a free, easy-to-use paint program for KDE
description: |
    KolourPaint is a free, easy-to-use paint program for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Widgets)
    - kdelibs4support-devel
    - libkexiv2-devel
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
